import{a as w,S as v,i as L}from"./assets/vendor-b0d10f48.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))l(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();async function b(e){return(await w.get(`https://pixabay.com/api/?${e}`)).data}const q="/goit-js-hw-12/assets/info-28eb2f9b.svg",E="/goit-js-hw-12/assets/icon-error-9681c3d4.svg",S={info:q,error:E},I=new v(".gallery li a");function f(e,t){const l={error:"red",info:"blue",success:"green"}[e.toLowerCase()];L.show({title:`${e}`,color:l,maxWidth:window.innerWidth<768?"100%":"33%",iconUrl:S[e.toLowerCase()],position:"topRight",message:`${t}`})}function x(e){return`<li>
            <a href="${e.largeImageURL}"><img src='${e.webformatURL}' alt='${e.tags}'></a>
            <div class="content">
                <div class="item"><h3>Likes</h3><p>${e.likes}</p></div>
                <div class="item"><h3>Views</h3><p>${e.views}</p></div>
                <div class="item"><h3>Comments</h3><p>${e.comments}</p></div>
                <div class="item"><h3>Downloads</h3><p>${e.downloads}</p></div>
            </div>
        </li>`}function P(e){return e.map(t=>x(t)).join("")}function m(e){e.innerHTML=""}function R(e,t){t.insertAdjacentHTML("beforeend",e),I.refresh()}class ${constructor(){this.element=document.querySelector(".js-loader-text"),this.options={text:"Loading images, please wait",loader:".",count:3}}show(){this.element.classList.remove("js-hidden");let t=0;this.interval=setInterval(()=>{t>this.options.count&&(t=0),this.element.innerText=this.options.text.padEnd(this.options.text.length+t,this.options.loader),t++},200)}remove(){clearInterval(this.interval),this.element.classList.add("js-hidden")}}function D(){const e=document.querySelector(".gallery li");if(e){const{height:t}=e.getBoundingClientRect();window.scrollBy({top:(t+20)*2,behavior:"smooth"})}}const s={btn:document.querySelector('button[data-request="load-more"]'),show(){s.btn.classList.remove("js-hidden")},hide(){s.btn.classList.add("js-hidden")}},a={form:document.querySelector("form"),gallery:document.querySelector(".photo-list")},u={inputEmpty:"Search input must be filled!",noData:"We're sorry, but you've reached the end of search results.",wrongInput:"Sorry, there are no images matching your search query. Please try again!"},h=new $;let c=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}),n={request_page:1,perPage:c.get("per_page")};const p={pageLimit(e){return n.limit=Math.ceil(e.totalHits/n.perPage),n.request_page>=n.limit},hits(e){return!e.hits||e.hits.length==0}};function g(e,t){console.log(t),f("Error",e),h.remove()}function O(e,t){if(p.hits(e)){g(u.noData,new Error("No data")),s.hide(),m(a.gallery);return}if(t||m(a.gallery),R(P(e.hits),a.gallery),p.pageLimit(e))throw s.hide(),new Error("No more pages");s.show()}async function y(e,t){h.show(),setTimeout(async()=>{try{const i=await b(c);O(i,t),h.remove()}catch(i){g(e,i)}},2e3)}a.form.addEventListener("submit",async e=>{e.preventDefault(),n.request_page=1;const t=a.form.elements[0].value.trim();if(!t){f("Info",u.inputEmpty);return}c.set("q",t),c.set("page",1),await y(u.noData,!1)});s.btn.addEventListener("click",async e=>{e.preventDefault(),s.hide(),c.set("page",++n.request_page),await y(u.wrongInput,!0),D()});
//# sourceMappingURL=commonHelpers.js.map
