import{a as p,S as f,i as g}from"./assets/vendor-b0d10f48.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function u(r){try{return(await p.get(`https://pixabay.com/api/?${r}`)).data}catch(e){console.log(e)}}const v="/goit-js-hw-12/assets/info-28eb2f9b.svg",y="/goit-js-hw-12/assets/icon-error-9681c3d4.svg",w={info:v,error:y},L=new f(".gallery li a");function h(r,e){const i={error:"red",info:"blue",success:"green"}[r.toLowerCase()];g.show({title:`${r}`,color:i,maxWidth:window.innerWidth<768?"100%":"33%",iconUrl:w[r.toLowerCase()],position:"topRight",message:`${e}`})}function q(r){return`<li>
            <a href="${r.largeImageURL}"><img src='${r.webformatURL}' alt='${r.tags}'></a>
            <div class="content">
                <div class="item"><h3>Likes</h3><p>${r.likes}</p></div>
                <div class="item"><h3>Views</h3><p>${r.views}</p></div>
                <div class="item"><h3>Comments</h3><p>${r.comments}</p></div>
                <div class="item"><h3>Downloads</h3><p>${r.downloads}</p></div>
            </div>
        </li>`}async function m(r,e,o){const i=r.map(t=>q(t)).join("");o||(e.textContent=""),e.insertAdjacentHTML("beforeend",i),L.refresh()}class E{constructor(){this.element=document.querySelector(".js-loader-text"),this.options={text:"Loading images, please wait",loader:".",count:3}}createInterval({count:e,text:o,loader:i}){this.element.classList.remove("js-hidden");let t=0;this.interval=setInterval(()=>{t>e&&(t=0),this.element.innerText=o.padEnd(o.length+t,i),t++},200)}removeInterval(e){clearInterval(e),this.element.classList.add("js-hidden")}init(){this.element.classList.add("js-hidden")}}const a={searchForm:document.querySelector("form"),photoList:document.querySelector(".photo-list"),loadMore:document.querySelector('button[data-request="load-more"]')},c=new E;c.init();let l=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",q:"",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:50}),n={};n.request_page=1;a.searchForm.addEventListener("submit",async r=>{r.preventDefault();const e=a.searchForm.elements[0].value.trim();if(!e){h("Info","Search input must be filled!");return}l.set("q",e),n.request_page=1;try{c.createInterval(c.options);const o=await u(l);if(!o.hits||o.hits.length===0)throw new Error("Error! Nothing to load");await m(o.hits,a.photoList,!1),c.removeInterval(c.interval),a.loadMore.classList.remove("js-hidden")}catch{h("Error","We're sorry, but you've reached the end of search results.")}});a.loadMore.addEventListener("click",async r=>{r.preventDefault(),a.loadMore.classList.add("js-hidden"),l.set("page",++n.request_page),n.perPage=l.get("per_page");try{const e=await u(l);if(!e.hits||e.hits.length===0)throw new Error("Error! Nothing to load");await m(e.hits,a.photoList,!0);const o=document.querySelector(".gallery li");if(o){const{height:i}=o.getBoundingClientRect();window.scrollBy({top:(i+20)*2,behavior:"smooth"})}if(n.limit=Math.ceil(e.totalHits/n.perPage),n.limit<n.request_page)throw a.loadMore.classList.add("js-hidden"),new Error("Error! Nothing to load");c.removeInterval(c.interval),a.loadMore.classList.remove("js-hidden")}catch{h("Error","Sorry, there are no images matching your search query. Please try again!")}});
//# sourceMappingURL=commonHelpers.js.map
