import{a as g,S as p,i as y}from"./assets/vendor-b0d10f48.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();async function u(t){try{return(await g.get(`https://pixabay.com/api/?${t}`)).data}catch(e){console.log(e)}}const v="/goit-js-hw-12/assets/info-28eb2f9b.svg",w="/goit-js-hw-12/assets/icon-error-9681c3d4.svg",L={info:v,error:w},E=new p(".gallery li a");function h(t,e){const n={error:"red",info:"blue",success:"green"}[t.toLowerCase()];y.show({title:`${t}`,color:n,maxWidth:window.innerWidth<768?"100%":"33%",iconUrl:L[t.toLowerCase()],position:"topRight",message:`${e}`})}function q(t){return`<li>
            <a href="${t.largeImageURL}"><img src='${t.webformatURL}' alt='${t.tags}'></a>
            <div class="content">
                <div class="item"><h3>Likes</h3><p>${t.likes}</p></div>
                <div class="item"><h3>Views</h3><p>${t.views}</p></div>
                <div class="item"><h3>Comments</h3><p>${t.comments}</p></div>
                <div class="item"><h3>Downloads</h3><p>${t.downloads}</p></div>
            </div>
        </li>`}async function m(t,e,o){const n=t.map(r=>q(r)).join("");o||(e.textContent=""),e.insertAdjacentHTML("beforeend",n),E.refresh()}class S{constructor(){this.element=document.querySelector(".js-loader-text"),this.options={text:"Loading images, please wait",loader:".",count:3}}init({count:e,text:o,loader:n}){this.element.classList.remove("js-hidden");let r=0;this.interval=setInterval(()=>{r>e&&(r=0),this.element.innerText=o.padEnd(o.length+r,n),r++},200)}remove(e){clearInterval(e),this.element.classList.add("js-hidden")}init(){this.element.classList.add("js-hidden")}}const i={form:document.querySelector("form"),gallery:document.querySelector(".photo-list"),loadMore:document.querySelector('button[data-request="load-more"]')},l=new S;l.init();let c=new URLSearchParams({key:"7706316-da1567048322714709989c4f8",image_type:"photo",orientation:"horizontal",safesearch:!0,page:1,per_page:15}),a={};a.request_page=1;function f(){return a.limit=Math.ceil(data.totalHits/a.perPage),a.limit<a.request_page}function P(){const t=document.querySelector(".gallery li");if(t){const{height:e}=t.getBoundingClientRect();window.scrollBy({top:(e+20)*2,behavior:"smooth"})}}i.form.addEventListener("submit",async t=>{t.preventDefault(),console.log(a);const e=i.form.elements[0].value.trim();if(!e){h("Info","Search input must be filled!");return}c.set("q",e),a.request_page=1;try{l.init(l.options);const o=await u(c);if(!o.hits||o.hits.length===0)throw new Error("Error! Nothing to load");if(await m(o.hits,i.gallery,!1),f())throw i.loadMore.classList.add("js-hidden"),new Error("Error! Nothing to load");l.remove(l.interval),i.loadMore.classList.remove("js-hidden")}catch{h("Error","We're sorry, but you've reached the end of search results.")}});i.loadMore.addEventListener("click",async t=>{t.preventDefault(),console.log(a),i.loadMore.classList.add("js-hidden"),c.set("page",++a.request_page),a.perPage=c.get("per_page");try{const e=await u(c);if(!e.hits||e.hits.length===0)throw new Error("Error! Nothing to load");if(await m(e.hits,i.gallery,!0),P(),f())throw i.loadMore.classList.add("js-hidden"),new Error("Error! Nothing to load");l.removeInterval(l.interval),i.loadMore.classList.remove("js-hidden")}catch{h("Error","Sorry, there are no images matching your search query. Please try again!")}});
//# sourceMappingURL=commonHelpers.js.map
